### ISSUE TITLE
Impossible to run "npm run build"

### ISSUE THREAD

**Issue by bmontassier** [lookitscook/kiosk#363]
**Describe the bug**
Hello, i have errors when i do npm run build

**To Reproduce**
1. Clone the repo
2. Do npm install
3. Do npm run build
4. See errors

![Deepin Capture-écran_zone de sélection _20190626093508](https://user-images.githubusercontent.com/35603054/60160552-e4a04080-97f5-11e9-94bf-0aec6e52a5ec.png)
![Deepin Capture-écran_zone de sélection _20190626093603](https://user-images.githubusercontent.com/35603054/60160562-e8cc5e00-97f5-11e9-8e69-79da458363ee.png)
![Deepin Capture-écran_zone de sélection _20190626093445](https://user-images.githubusercontent.com/35603054/60160602-ff72b500-97f5-11e9-87b3-7d9c620c11d9.png)

**Comment by itcthienkhiem** [comment]
how fixed?
