### ISSUE TITLE
Wrong url, cannot access admin

### ISSUE THREAD

**Issue by alibarrak** [lookitscook/kiosk#381]
if I put wrong URL or LAN URL that sometime gets unreachable I get locked in:
"This site can't be reached...... ERR_ADDRESS_UNREACHABLE"

And I cannot use CTRL+A to change the settings (it works as select all)

Any workarounds?

**Comment by kaiuhl** [comment]
This is also affecting us and is a real bother.

**Comment by matt-cook** [comment]
Need to confirm this is still happening with latest version (system level key shortcuts instead of page events). In theory, it shouldn't be.

**Comment by alibarrak** [comment]
just tested the new version and I can confirm the issue has been resolved.
